### ISSUE TITLE
badge stays on 'queued'

### ISSUE THREAD

**Issue by MauriceGit** [avelino/cover.run#20]
https://cover.run/go?tag=golang-1.10&repo=https%3A%2Fgithub.com%2FMauriceGit%2Fskiplist

https://github.com/MauriceGit/skiplist

I created the badge (and integrated into my Readme) 6 days ago. Since then it stays on queued status.
There are also some repositories with the badge integrated months ago where the badge is still on queued.
(Like this: https://github.com/bnkamalesh/webgo)

Is there any way to make it work?

**Comment by bitfield** [comment]
Same problem here.

**Comment by bnkamalesh** [comment]
@MauriceGit the issue is because you gave the full HTTP URL of the repository instead of just the import path. 

Please check this:

[![cover.run](https://cover.run/go/github.com/MauriceGit/skiplist.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2FMauriceGit%2Fskiplist) 

https://cover.run/go?repo=github.com%2FMauriceGit%2Fskiplist&tag=golang-1.10

P.S: This can  be a bugfix/feature where the app can omit `http(s)://` and continue the cover run.

Edit: [webgo](https://github.com/bnkamalesh/webgo) shows the queued badge (not forever) because it's actually queued and being processed. The coverage is cached and re-run every 1hr, hence you see queued instead of the actual coverage. Since there is no git hook to automatically re-run only when there is a change in code, it runs every 1hr.

**Comment by bitfield** [comment]
If I remove the `https:` from the repo, I just get a 'Repository not found' error: https://cover.run/go?repo=github.com%2Fbitfield%2Fuptimerobot%2Fpkg&tag=golang-1.10

**Comment by bnkamalesh** [comment]
Hey @bitfield, please check this issue https://github.com/avelino/cover.run/issues/19

**Comment by MauriceGit** [comment]
It works for me, thanks!
